#Informacion del proyecto
info:
  project:
    title: KENPIS - Sistema de Ventas
    name: KENPIS
    description: KENPIS - Sistema de Ventas Online Simple Y Facil
    version: 0.1.0-SNAPSHOT

#Configuracion del Servidor
server:
  port: 8080
  servlet:
    context-path:

#Configuraciones para Spring - Base de Datos
spring:
  profiles:
    active: dev
  application:
    name: KENPIS
  devtools:
    add-properties: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  datasource:
    #url: jdbc:sqlserver://161.132.55.86:1433;database=BD_KENPIS_DEV
    url: jdbc:sqlserver://161.132.55.86:1433;database=BD_KENPIS_DEV
    username: SA
    password: Lima1234..
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # Opcional: muestra las consultas SQL en la consola
        format_sql: true # Opcional: formatea las consultas SQL para facilitar la lectura
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: off

#Path para Logs
logging:
  level:
    web: INFO
    #org.hibernate.sql: DEBUG
    #org.hibernate.type: TRACE
    #org.springframework.web: INFO
    #guru.springframework.controllers: INFO
