select * from T_USUARIO;
select * from T_USUARIO_AUTHORITY;
select * from T_CLIENTE;
select * from T_VENTA;
select * from T_VENTA_DETALLE;
select * from T_VENTA_ESTADO;


CREATE PROCEDURE SP_COUNT_PEDIDOS_X_ESTADO
AS
BEGIN
    SELECT SUM(CASE WHEN ven_estado = 'REGISTRADO' THEN 1 ELSE 0 END) AS REGISTRADO,
           SUM(CASE WHEN ven_estado = 'PAGADO' THEN 1 ELSE 0  END) AS PAGADO,
           SUM(CASE WHEN ven_estado = 'EN_PROCESO' THEN 1 ELSE 0 END) AS EN_PROCESO,
           SUM(CASE WHEN ven_estado = 'ATENDIDO' THEN 1 ELSE 0 END) AS ATENDIDO,
           SUM(CASE WHEN ven_estado = 'DESCARTADO' THEN 1 ELSE 0 END) AS DESCARTADO
    FROM T_VENTA_ESTADO
END
GO